<a href="https://colab.research.google.com/github/dymiyata/wva-ml-ai-1-2026-2027/blob/main/intro_to_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Working With Data Using the Pandas Library

To do any sort of machine learning, we first need to be comfortable working with data.  After all, data is the backbone of machine learning.

Here we will give an overview to working with the `pandas` library.  

This is a library used to work with datasets.  
Think of it like Google Sheets or Microsoft Excel but using Python.

## Housekeeping

Before We begin, save a copy of this notebook to your own google drive.
To do this click File->Save a copy in Drive.

Once you're in the copy, rename the file to 'intro_to_pandas_\<insert your name here\>`

## Importing Pandas

`pandas` is python libary so in order to access its functionality, we need to import it.  If you are running things locally on your machine (i.e. not in google colab) then you will have to install `pandas` before you can use it.

Here is a link to the pandas documentation: [pandas docs](https://pandas.pydata.org/docs/)

In [6]:
import pandas as pd

## Importing the dataset

The dataset we'll use today came from a website called [Kaggle](https://www.kaggle.com/).
* Kaggle is a great source for those looking to do data science or machine learning
* You can find many datasets, competitions, and example notebooks
* Feel free to explore Kaggle on your free time

The specific data set we are using is a dataset consisting of the first 721 pokemon.

![International_Pokémon_logo.svg]()

The following code will import the data set.  For now, don't worry too much about how it works.  It simply downloads the dataset from Kaggle so we can work with it.

The dataset is stored in a .csv file.
* This stands for 'comma-separated values'
* It is just a big text file for storing a table of data
* The different values in the table are separated with commas (hence the name)

### Using Pandas

The `pandas` library primarily uses a data type called a *dataframe*. This is the primary data type that we will store our data into in this class.

The code below reads the `Pokemon.csv` file that we downloaded and creates a pandas dataframe.  
* Remember we imported `pandas` as `pd`

Then, we take that dataframe and store it in the variable df.

In [7]:
# If you run into an error try running the previous cell again
# If it still doesn't work, you may need to adjust the path to the file
# Check the printed output of the previous cell to find the right path

df = pd.read_csv("https://raw.githubusercontent.com/dymiyata/wva-ml-ai-1-2026-2027/refs/heads/main/Pokemon.csv")

Let's explore the data set a bit
* `DataFrame.head()` and `DataFrame.tail()` return the first few rows and the last few rows of the dataframe respectively.
* If you pass an integer `n` as an argument to either function, it'll return exactly `n` rows.

Let's run some of these to get a feel for what our dataset looks like

In [10]:
df.head(17)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False

In [11]:
df.tail(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Now let's try the following functions.  See if you can figure out what they do:
* `DataFrame.info()`
* `DataFrame.describe()`

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [13]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

We can also sort our data using any of the columns. Suppose we want to sort the pokemon based on their speed.  We'd use the following command

`df.sort_values(by="Speed")`

In [ ]:
alist = [1,2,3]
alist.append

In [19]:
df.sort_values(by="Attack", ascending=False)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
424,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
488,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False

How can we figure out which pokemon has the highest *HP* stat?

In [21]:
df.sort_values(by="HP", ascending=False).head(1)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False

Suppose we don't care about all the stats. We just care about the names of the pokemon. Let's run the following command:
`df["Name"]`

In [25]:
df[["Name", "HP"]]

                      Name  HP
0                Bulbasaur  45
1                  Ivysaur  60
2                 Venusaur  80
3    VenusaurMega Venusaur  80
4               Charmander  39
..                     ...  ..
795                Diancie  50
796    DiancieMega Diancie  50
797    HoopaHoopa Confined  80
798     HoopaHoopa Unbound  80
799              Volcanion  80

[800 rows x 2 columns]

Now suppose we want to entries based on their labels (either row labels or column labels).

For this we have the `DataFrame.loc()` functions.

Try `df.loc[0, ["Name", "Legendary"]]`

Then try `df.loc[0:10, ["Name", "Legendary"]]`

Next, try `df.loc[:, ["Name", "Legendary"]]`

What about `df.loc[12:15, "Name":"Attack"]`

In [31]:
df.loc[4, ["Name", "Legendary", "Attack"]]

Name         Charmander
Legendary         False
Attack               52
Name: 4, dtype: object

In [40]:
my_list = list(range(0,9))
print(my_list)
print(my_list[:4])

[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0, 1, 2, 3]

In [37]:
df.loc[0:10, ["Name", "Legendary"]]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False

In [41]:
df.loc[:, ["Name", "Legendary"]]

                      Name  Legendary
0                Bulbasaur      False
1                  Ivysaur      False
2                 Venusaur      False
3    VenusaurMega Venusaur      False
4               Charmander      False
..                     ...        ...
795                Diancie       True
796    DiancieMega Diancie       True
797    HoopaHoopa Confined       True
798     HoopaHoopa Unbound       True
799              Volcanion       True

[800 rows x 2 columns]

How can we return a dataframe consisting of  the `"Name"` and all 6 stats (`"HP"`, `"Attack"`, `"Defense"`, `"Sp. Atk"`, `"Sp. Def"`, `"Speed"`) for the 60th to 67th pokemon?

In [42]:
df.loc[60:67, ["Name", "HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]]

         Name  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
60    Golduck  80      82       78       95       80     85
61     Mankey  40      80       35       35       45     70
62   Primeape  65     105       60       60       70     95
63  Growlithe  55      70       45       70       50     60
64   Arcanine  90     110       80      100       80     95
65    Poliwag  40      50       40       40       40     90
66  Poliwhirl  65      65       65       50       50     90
67  Poliwrath  90      95       95       70       90     70

Instead of using the labels, we can also use indices for the rows and columns.  For example `"#"` is column `0`, `"Name"` is colmun `1`, `"Type 1"` is column `2`, etc...

This is done using the `DataFrame.iloc()` command.  This is very similar to `DataFrame.loc()` except you use indices, not the actual labels. The "i" in "iloc" stands for index or indices.

For example, try running the following:
`df.iloc([0, 1, 2], [1,2,3])`.
Can you see how this function works?

Again let's return a dataframe consisting of  the `"Name"` and all 6 stats (`"HP"`, `"Attack"`, `"Defense"`, `"Sp. Atk"`, `"Sp. Def"`, `"Speed"`) for the 60th to 67th pokemon.  However, this time use the `DataFrame.iloc` function

We can also use booleans to filter our dataframe.

Try running the following command:
`df[df["Type 1"]=="Psychic"]`

Then try `df[(df["Type 1"]=="Psychic") & (df["Legendary"]==True)]`

Then try `df[df["Name"].str.startswith("W")]`

Then try `df[df["Type 1"].isin(["Fire", "Ghost", "Normal"])]`

Lastly, try `df[df["Attack"] > 100]`

What if you add `.info()` to the end of any of these?

In [44]:
df[(df["Type 1"]=="Psychic") & (df["Type 2"]=="Fighting")]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
526,475,Gallade,Psychic,Fighting,518,68,125,65,65,115,80,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,618,68,165,95,65,115,110,4,False

In [45]:
df[(df["Type 1"]=="Psychic") | (df["Type 2"]=="Fighting")]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
67,62,Poliwrath,Water,Fighting,510,90,95,95,70,90,70,1,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
69,64,Kadabra,Psychic,NaN,400,40,35,30,120,70,105,1,False
70,65,Alakazam,Psychic,NaN,500,55,50,45,135,95,120,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,677,Espurr,Psychic,NaN,355,62,48,54,63,60,68,6,False
746,678,MeowsticMale,Psychic,NaN,466,74,48,76,83,81,104,6,False
747,678,MeowsticFemale,Psychic,NaN,466,74,48,76,83,81,104,6,False
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True

How would you figure out how many pokemon are psychic type and also have a Speed stat of at least 120?

Next we'll create a copy of `df` so that I can edit things without changing the original dataframe. We'll call this copy `df_copy`
* Adding the argument `deep=True` ensures that changing the values in the copy, won't also change values in the original

In [ ]:
df_copy = df.copy(deep=True)

Let's add a new column to `df_copy`

Try running `df_copy["Attack Speed Ratio"] = df_copy["Attack"] / df_copy["Speed"]`

Then use `df_copy.head()` to see the results

There are many more things we can do with `pandas` dataframes.  This is only scratching the surface.  If you ever have something you want to be able to do, you can puruse the documentation I linked above or always try googling whatever it is you want to do (I do this all the time).

Your goal with learning pandas should just be to build familiarity with it.  You won't be expected to memorize all of the functions.  Instead, as long as you know *what* you can do, you can always do a google search to figure out *how* to do it.

# **Homework 1**

Below, we have homework number 1.

These problems will use the dataframe of pokemon data that we used in class.  This should be called `df` in this notebook.  

If your runtime stopped, you may have to run the earlier cells that we used to download the data and define the dataframe.

## Instructions for Homework
* For each problem, find a way to work with the dataframe to answer each questions
* Show any relevant functions/code you used in order to get to your answer
* Have your answer clearly stated by using a text cell
  * At the top of the window you should see "+ Code" and "+ Text" buttons. To add a text cell click the "+ Text" button. If you want to try formatting things nicely, look up the markdown markup language.
  * You could write something like "Problem 5 answer: \<type answer here\>"
  * Feel free to format your answer how you see fit.  Just make sure it's clear to me what your answer is.
* This homework (and probably most) will be graded mostly for completion. If you get stuck on a problem but it's clear that you made an effort then that's mainly what I'll look for.
  * Keep the code you write, even if you don't figure out how to solve a problem.
  * If you do get stuck, please also write a short explanation of what you tried and what ended up happening.  It's really good to practice explaining what you're having trouble with.  The people who do this the best usually end up learning the most.
* Try to solve each problem just using things we've covered here (unless I specifically suggest looking up something). If you still need further help you can turn to google (Do not use ChatGPT or some other LLM). However don't just search how to solve this specific problem.
  * Instead think about what specific functionality you might need to figure out a certain step in a problem. Then search for how to use Pandas to do that.
    * Don't search, "If I have a dataframe of pokemon and their stats, how do I \<insert problem here\>". You will probably not learn this way.
    * Searching something like: "How do I sort a Pandas dataframe based on a certain column" is totally fine.
  * Then make sure you understand each step of whatever code examples you find and try to apply that knowledge to your use case.

### HW Problem 1

Find the average `Total` stat for Legendary Pokemon. Then do the same for non-Legendary pokemon.  Which is bigger? Does this seem reasonable to you?

*Optional challenge:* Figure out which type has the *most* legendary pokemon. For this, try googling the `value_counts()` function for Pandas.

### HW Problem 2

Find the five pokemon who are water type with the highest HP stat.
* Note: A pokemon is considered water type as long as at least one of `Type 1` or `Type 2` is water.

### HW Problem 3

Figure out how many pokemon have a higher Attack stat than Defense stat.

### HW Problem 4

Which generation had the fastest pokemon on average?

### HW Problem 5

Create your own stat that you think measures something interesting by combining existing stats (Get Creative!).
* For example, maybe doing `(Attack + Sp. Atk + HP)/3` (i.e. the average of these three stats) measures some sort of "bulkiness". If this is high, it seems the pokemon can hit hard, but also take a lot of hits. (Don't use this example)
* Give a name to this new stat and create a new column for it
* Find the top 5 pokemon based on this metric
* Explain why you think your new stat is interesting and meaningful (this can just be a couple sentences).

### HW Problem 6

What's your favorite pokemon? (for those familiar with pokemon, you can only pick from generations 1 to 6... sorry)
* If you don't really have one or aren't so familiar with pokemon, pick a number and use the pokemon with that `#`.

When ranking the pokemon by speed, where does your chosen pokemon rank?